baseURL = 'https://ihatejazz-original.github.io/carbon-net-neutral-project/'
languageCode = 'en-us'
title = 'Carbon Net Neutral Project'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
